import { create } from 'zustand';
import { persist } from 'zustand/middleware';

const translations = {
  en: {
    dashboard: "Overview",
    register_issue: "Report an Issue",
    regional_network: "Community Chat",
    control_center: "Admin Panel",
    logout: "Logout",
    welcome: "Welcome",
    citizen_karma: "Your Reputation",
    city_impact: "Community Impact",
    resolution_rate: "Success Rate",
    response_time: "Avg. Wait Time",
    satisfaction: "Citizens' Vote",
    active_officials: "Officials Online",
    search_placeholder: "Search for issues...",
    no_records: "No issues found",
    submit_protocol: "File a Report",
    grievance_subject: "Issue Title",
    detail_matrix: "Describe the Problem",
    upload_visual: "Add Photos/Videos",
    target_department: "Who should fix this?",
    ward_node: "Select Your Area",
    impact_magnitude: "People Affected",
    anonymous_mode: "Hide My Identity",
    register_case: "Submit Report",
    language: "Language",
    kerala_node: "Kerala Center",
    leaderboard: "Top Citizens",
    india: "India",
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    register_issue: "പരാതി രജിസ്റ്റർ ചെയ്യുക",
    regional_network: "പ്രാദേശിക ശൃംഖല",
    control_center: "നിയന്ത്രണ കേന്ദ്രം",
    logout: "ലോഗൗട്ട്",
    welcome: "സ്വാഗതം",
    citizen_karma: "സിറ്റിസൺ സിസ്വം",
    city_impact: "നഗര പ്രഭാവം",
    resolution_rate: "പരിഹാര നിരക്ക്",
    response_time: "പ്രതികരണ സമയം",
    satisfaction: "പൗര സംതൃപ്തി",
    active_officials: "ഔദ്യോഗിക പ്രതിനിധികൾ",
    search_placeholder: "തിരയുക...",
    no_records: "വിവരങ്ങൾ ലഭ്യമല്ല",
    submit_protocol: "പരാതി സമർപ്പിക്കുക",
    grievance_subject: "പരാതി വിഷയം",
    detail_matrix: "വിശദാംശങ്ങൾ",
    upload_visual: "ചിത്രം/വീഡിയോ ചേർക്കുക",
    target_department: "വകുപ്പ് തിരഞ്ഞെടുക്കുക",
    ward_node: "വാർഡ്",
    impact_magnitude: "പ്രഭാവത്തിന്റെ തോത്",
    anonymous_mode: "രഹസ്യമായി സമർപ്പിക്കുക",
    register_case: "രജിസ്റ്റർ ചെയ്യുക",
    language: "ഭാഷ",
    kerala_node: "കേരള നോഡ്",
    leaderboard: "മികച്ച പൗരന്മാർ",
    india: "ഇന്ത്യ",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    register_issue: "मुद्दा दर्ज करें",
    regional_network: "क्षेत्रीय नेटवर्क",
    control_center: "नियंत्रण केंद्र",
    logout: "लोग आउट",
    welcome: "स्वागत है",
    citizen_karma: "नागरिक कर्मा",
    city_impact: "शहर प्रभाव",
    resolution_rate: "समाधान दर",
    response_time: "प्रतिक्रिया समय",
    satisfaction: "नागरिक संतुष्टि",
    active_officials: "सक्रिय अधिकारी",
    search_placeholder: "खोजें...",
    no_records: "कोई रिकॉर्ड नहीं मिला",
    submit_protocol: "प्रोटोकॉल सबमिट करें",
    grievance_subject: "शिकायत का विषय",
    detail_matrix: "विवरण मैट्रिक्स",
    upload_visual: "विजुअल अपलोड करें",
    target_department: "लक्षित विभाग",
    ward_node: "वार्ड नोड",
    impact_magnitude: "प्रभाव परिमाण",
    anonymous_mode: "अनाम मोड",
    register_case: "केस दर्ज करें",
    language: "भाषा",
    kerala_node: "केरल नोड",
    leaderboard: "शीर्ष नागरिक",
    india: "भारत",
  }
};

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      currentLanguage: 'en',
      languages: [
        { code: 'en', name: 'English', flag: '🇬🇧' },
        { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
        { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
      ],
      setLanguage: (code) => set({ currentLanguage: code }),
      t: (key) => translations[get().currentLanguage][key] || key,
    }),
    { name: 'civix-language' }
  )
);
